Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  DefaultFormatter: progress
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
Metrics/LineLength:
  Max: 99
