language: ruby
rvm:
  - 2.5.0
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rake db:setup
  - bundle exec rspec
