# language: ruby
# rvm: 2.5.3
# services:
#   - postgresql
#   - xvfb
# addons:
#   chrome: stable
# env:
#   - RAILS_ENV=test
# before_script:
#   - psql -c 'create database travis_ci_test;' -U postgres
#   - export DISPLAY=:99.0
# script:
#   - bundle exec rake db:setup
#   - bundle exec rspec
